name: Gradle Package

on:
  push:
    tags:
    - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: olegtarasov/get-tag@v2.1.3
      id: tagName
    - uses: actions/checkout@v4.1.1
    - name: Set up JDKS
      uses: actions/setup-java@v4.2.1
      with:
        java-version: |
          '22.0.1'
          '21.0.1'
        distribution: 'temurin'
        architecture: x64

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew createReleaseLinux
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        draft: true
        bodyFile: ".github/releasenotes.txt"
        artifacts: "output/*.*"
        name: "Elite Dangerous Odyssey Materials Helper ${{ steps.tagName.outputs.tag }}"
        
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: olegtarasov/get-tag@v2.1.3
      id: tagName
    - uses: actions/checkout@v4.1.1
    - name: Set up JDKS
      uses: actions/setup-java@v4.2.1
      with:
        java-version: |
          '22.0.1'
          '21.0.1'
        distribution: 'temurin'
        architecture: x64

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew createRelease
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        draft: true
        bodyFile: ".github/releasenotes.txt"
        artifacts: "output/*.*"
        name: "Elite Dangerous Odyssey Materials Helper ${{ steps.tagName.outputs.tag }}"

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-ubuntu]
    permissions:
      contents: write
    steps:
      - name: Publish Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: true
